# Generated by Django 5.1.6 on 2025-03-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_fooditem_category'),
        ('vendor', '0004_alter_vendor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('vendor', 'category_name'), name='unique_category_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.UniqueConstraint(fields=('vendor', 'food_title'), name='unique_food_title_per_vendor'),
        ),
    ]
