# Generated by Django 5.1.7 on 2025-03-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
