# Generated by Django 5.1.7 on 2025-04-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_data_order_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(blank=True, help_text="Data format: [{'type': tax_type,'percentage': tax_percentage,'amount': tax_amount}]", null=True),
        ),
    ]
